# Generated by Django 3.1.3 on 2023-11-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('a_paterno', models.TextField(default=0)),
                ('a_materno', models.TextField(default=0)),
                ('fechaNacimiento', models.DateField(default=0)),
                ('nacionalidad', models.TextField(default='')),
                ('biografia', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('isbn', models.IntegerField(default='')),
                ('tipoDeColeccion', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('fechaPublicacion', models.DateField(default='')),
                ('categoria', models.TextField(default='')),
                ('estado', models.TextField(default='')),
                ('ubicacioEnBiblioteca', models.TextField(default='')),
                ('precio', models.FloatField(default='')),
                ('id_Autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('a_paterno', models.TextField(default='')),
                ('a_materno', models.TextField(default='')),
                ('tipoDeUsuario', models.TextField(default='')),
                ('ciudad', models.TextField(default='')),
                ('correo', models.TextField(default='')),
                ('contrasena', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReserva', models.DateField(default='')),
                ('estadoReserva', models.TextField(default='')),
                ('id_coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.coleccion')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(default='')),
                ('fechaVencimiento', models.DateField(default='')),
                ('fechaDevolucion', models.DateField(default='')),
                ('estadoPrestamo', models.TextField(default='')),
                ('id_coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.coleccion')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadDisponible', models.IntegerField(default='')),
                ('cantidadTotal', models.IntegerField(default='')),
                ('fechaDeAdquisicion', models.DateField(default='')),
                ('id_Coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEnLinea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.TextField(default='')),
                ('id_coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.coleccion')),
                ('id_inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.inventario')),
            ],
        ),
    ]
