# Generated by Django 3.1.3 on 2023-11-16 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20231116_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='misCosas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAdquisicion', models.DateField(default='')),
                ('id_coleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.coleccion')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
