# Generated by Django 3.1.3 on 2023-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_miscosas'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='urlImagen',
            field=models.TextField(default=''),
        ),
    ]
